spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  secret: ${SECRET_KEY}
  lifetime: 30m
