spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host:
    port:
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
jwt:
  secret: ${SECRET_KEY}
  lifetime: 1d
server:
  port: 80
smsCode:
  lifetime: 30m